apiVersion: v1
kind: Service
metadata:
  name: insurance-model-service
spec:
  selector:
    app: insurance-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer